<a href="https://colab.research.google.com/github/Roman3173/RomanGo/blob/main/Test%20cases/3D_room_test/test_case_workplace_3d_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np
import json

In [ ]:
# image_1024_aligned_rgb.png
!gdown 1MEa-_oowpOuP2wa7zEmSM7uYxcgNAXxt

Downloading...
From: https://drive.google.com/uc?id=1MEa-_oowpOuP2wa7zEmSM7uYxcgNAXxt
To: /content/image_1024_aligned_rgb.png
100% 571k/571k [00:00<00:00, 117MB/s]


In [ ]:
# test_object_lu.json
!gdown 15qyneDxjA30lOdrZOHX80FrQVWSKIpnJ

Downloading...
From: https://drive.google.com/uc?id=15qyneDxjA30lOdrZOHX80FrQVWSKIpnJ
To: /content/test_object_lu.json
100% 194/194 [00:00<00:00, 651kB/s]


In [ ]:
# floor_plan_test.jpg
!gdown 1vlmfA20KIyGlHmhIoSzus4NFIAuoRFb9

Downloading...
From: https://drive.google.com/uc?id=1vlmfA20KIyGlHmhIoSzus4NFIAuoRFb9
To: /content/floor_plan_test.jpg
100% 17.8k/17.8k [00:00<00:00, 28.8MB/s]


In [ ]:
# v_corners.npy
!gdown 18cKH92wswG-_Hk-uZYqJmYeem6GMOafb

Downloading...
From: https://drive.google.com/uc?id=18cKH92wswG-_Hk-uZYqJmYeem6GMOafb
To: /content/v_corners.npy
100% 224/224 [00:00<00:00, 538kB/s]


In [ ]:
# h_corners.npy
!gdown 1VPSbwA8Y8roX7-nMnBuwtKRCGihRLhAY

Downloading...
From: https://drive.google.com/uc?id=1VPSbwA8Y8roX7-nMnBuwtKRCGihRLhAY
To: /content/h_corners.npy
100% 8.32k/8.32k [00:00<00:00, 15.9MB/s]


In [ ]:
# /content/depth_map.npy
!gdown 1x6YD2uk-ivS9uhosIkY75-k2hDVIhte6

Downloading...
From: https://drive.google.com/uc?id=1x6YD2uk-ivS9uhosIkY75-k2hDVIhte6
To: /content/depth_map.npy
100% 2.10M/2.10M [00:00<00:00, 48.0MB/s]


In [ ]:
panorama_image_path = "/content/image_1024_aligned_rgb.png"
panorama_image = cv2.imread(panorama_image_path, cv2.IMREAD_COLOR)

In [ ]:
floor_plan_path = "/content/floor_plan_test.jpg"
floor_plan = cv2.imread(panorama_image_path)

In [ ]:
json_path = "/content/test_object_lu.json"
with open(json_path, 'r') as json_file:
    walls_data = json.load(json_file)
walls_data

{'room_id': 0,
 'walls': {'0': [0, 0, 0, 2050],
  '1': [0, 0, 1640, 0],
  '2': [1640, 0, 1640, 400],
  '3': [1640, 400, 6020, 400],
  '4': [6020, 400, 6020, 2050],
  '5': [0, 2050, 6020, 2050]}}

In [ ]:
v_corners_path = "/content/v_corners.npy"
vertical_corners = np.load(v_corners_path)
vertical_corners

array([[  30.914364,  222.41164 ],
       [  30.914364,  298.64883 ],
       [ 363.15613 ,  140.81924 ],
       [ 363.15613 ,  392.54047 ],
       [ 672.78357 ,  149.66058 ],
       [ 672.78357 ,  383.4991  ],
       [ 801.5895  ,  137.09825 ],
       [ 801.5895  ,  396.26495 ],
       [ 845.40314 ,   76.09795 ],
       [ 845.40314 ,  451.50623 ],
       [1008.1279  ,  221.95033 ],
       [1008.1279  ,  299.23853 ]], dtype=float32)

In [ ]:
h_corners_path = "/content/h_corners.npy"
horizontal_corners = np.load(h_corners_path)
horizontal_corners

array([[221.67708, 221.43863, 221.38431, ..., 222.38773, 223.78665,
        223.0257 ],
       [299.86584, 298.79175, 299.72705, ..., 298.76703, 297.46896,
        299.3693 ]], dtype=float32)

In [ ]:
horizontal_corners.shape

(2, 1024)

In [ ]:
depth_map_path = "/content/depth_map.npy"
depth_map = np.load(depth_map_path)
depth_map

array([[1.2148892, 1.2148892, 1.2148892, ..., 1.2148892, 1.2148892,
        1.2148892],
       [1.2149348, 1.2149348, 1.2149348, ..., 1.2149348, 1.2149348,
        1.2149348],
       [1.2150264, 1.2150264, 1.2150264, ..., 1.2150264, 1.2150264,
        1.2150264],
       ...,
       [1.6001883, 1.6001883, 1.6001883, ..., 1.6001883, 1.6001883,
        1.6001883],
       [1.6000677, 1.6000677, 1.6000677, ..., 1.6000677, 1.6000677,
        1.6000677],
       [1.6000075, 1.6000075, 1.6000075, ..., 1.6000075, 1.6000075,
        1.6000075]], dtype=float32)

In [ ]:
panorama_image.shape

(512, 1024, 3)

# Проверка полученных данных. Построение панорамы с разметкой углов.

In [ ]:
# Загрузка изображения
panorama_image_path = "/content/image_1024_aligned_rgb.png"
p_i = cv2.imread(panorama_image_path, cv2.IMREAD_COLOR)

# Преобразование координат в целые числа (пиксели)
vertical_corners = np.around(vertical_corners, decimals = 0).astype(int)

# Нанесение точек на изображение
for point in vertical_corners:
    x, y = point
    size = 10  # Размер крестика
    color = (0, 165, 255)  # Оранжевый цвет в формате BGR
    thickness = 1  # Толщина линии
    # Диагональные крестики
    cv2.line(p_i, (x - size, y - size), (x + size, y + size), color, thickness)
    cv2.line(p_i, (x - size, y + size), (x + size, y - size), color, thickness)

# Сохранение изображения с точками
#cv2.imwrite("/content/image_with_points.jpg", p_i)

In [ ]:
for i in range(0, len(vertical_corners), 2):
    x1, y1 = vertical_corners[i][0], vertical_corners[i][1]
    x2, y2 = vertical_corners[i + 1][0], vertical_corners[i + 1][1]
    color = (255, 165, 0)
    thickness = 1  # Толщина линии
    # Диагональные крестики
    cv2.line(p_i, (x1, y1), (x2, y2), color, thickness)

In [ ]:
# Преобразование координат в целые числа (пиксели)
horizontal_corners = np.around(horizontal_corners, decimals = 0).astype(int)

# Нанесение точек на изображение
for i in range(len(horizontal_corners)):
    for j in range(1, len(horizontal_corners[0])):
        x1, y1 = j - 1, horizontal_corners[i][j - 1]
        x2, y2 = j, horizontal_corners[i][j]
        color = (255, 165, 0)
        thickness = 1  # Толщина линии
        # Диагональные крестики
        cv2.line(p_i, (x1, y1), (x2, y2), color, thickness)

# Сохранение изображения с точками
cv2.imwrite("/content/image_with_points_and_lines.jpg", p_i)

True

# Поиск высоты в углах помешения
По формуле медианы: зная 2 стороны треугольника и медиану, можно найти 3-ю сторону.

In [ ]:
x1 = vertical_corners[0][0]
y1 = vertical_corners[0][1]
y2 = vertical_corners[1][1]
ym = (y2 + y1) // 2
[x1, [y1, ym, y2]]

[31, [222, 260, 299]]

In [ ]:
AB = depth_map[y1][x1]
AC = depth_map[y2][x1]
AM = depth_map[ym][x1]

In [ ]:
[AB, AM, AC]

[5.952132, 5.887788, 6.066243]

In [ ]:
h1 = (2 * (AB ** 2 + AC ** 2) - 4 * AM ** 2) ** 0.5

In [ ]:
h1

2.4062807157265764

In [ ]:
v_corners_path = "/content/v_corners.npy"
vertical_corners = np.load(v_corners_path)
vertical_corners = np.around(vertical_corners, decimals = 0).astype(int)
high_corn = [0] * 6
for i in range(0, len(vertical_corners), 2):
    x1 = vertical_corners[i][0]
    y1 = vertical_corners[i][1]
    y2 = vertical_corners[i+1][1]
    yh = 255
    ym = (y2 + y1) // 2
    AB = depth_map[y1][x1]
    AC = depth_map[y2][x1]
    AH = depth_map[yh][x1]
    AM = depth_map[ym][x1]
    #high_corn[i // 2] = (2 * (AB ** 2 + AC ** 2) - 4 * AM ** 2) ** 0.5
    high_corn[i // 2] = ((AB ** 2 - AH ** 2) ** 0.5 + (AC ** 2 - AH ** 2) ** 0.5)

high_corn

[2.3571264241401773,
 2.804948554516445,
 2.797412369415208,
 2.778131745762649,
 2.8096198494045748,
 2.7805755030831425]

In [ ]:
x_min = vertical_corners[2][0]
x_max = vertical_corners[4][0]
depth_1_wall = depth_map[255][x_min:x_max]
depth_1_wall[148:150] - min(depth_1_wall)
center_1_wall = 149
HH = (2 * depth_1_wall[0]**2 + 2 * depth_1_wall[-1]**2 - 4 * depth_1_wall[center_1_wall] ** 2) ** 0.5
HH / 2.05

1.200122789218613

Медианы всех углов, кроме первого, ~= 2.8, из друх рассчётов предположу, что 2.8 метра.

In [ ]:
wall_height = 2.8 / 1.2

# Попытка применить Афинное преобразование.

In [ ]:
panorama_image_path = "/content/image_1024_aligned_rgb.png"
new_pan = cv2.imread(panorama_image_path, cv2.IMREAD_COLOR)
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
first_point = []
mask = np.zeros_like(new_pan)
for i in range(x1, x2 + 1):
    mask[horizontal_corners[0][i]: horizontal_corners[1][i], i] = 1

# Примените маску к панораме
result = new_pan * mask

    # Сохраните результат
cv2.imwrite("/content/segmented.jpg", result)

True

In [ ]:
panorama_image_path = "/content/image_1024_aligned_rgb.png"
new_pan = cv2.imread(panorama_image_path, cv2.IMREAD_COLOR)
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]

mask = np.zeros_like(new_pan)
for i in range(x1, x2 + 1):
    mask[horizontal_corners[0][i]: horizontal_corners[1][i], i] = 1

point1 = [x1, horizontal_corners[0][x1]]
point4 = [x1, horizontal_corners[1][x1]]
point2 = [x2, horizontal_corners[0][x2]]
point3 = [x2, horizontal_corners[1][x2]]

# Примените маску к панораме
result = new_pan * mask
wall_width = 602
wall_height = 233

src_points = np.array([point1, point2, point3, point4], dtype=np.float32)
dst_points = np.array([[0, 0], [wall_width, 0], [wall_width, wall_height], [0, wall_height]], dtype=np.float32)

# Получите матрицу преобразования
perspective_matrix = cv2.getAffineTransform(src_points[:3], dst_points[:3])

# Примените преобразование
result_rectangular = cv2.warpAffine(result, perspective_matrix, (wall_width, wall_height), flags = cv2.INTER_NEAREST)
# Сохраните результат
cv2.imwrite("/content/rectangular_result.jpg", result_rectangular)

True

# Попытка влоб обратить fisheye эффект (неудачно)

In [ ]:
perspective_matrix

array([[   1.81325301,    0.        ,  -56.21084337],
       [   0.22746321,    0.92094862, -211.50195247]])

In [ ]:
dst_points

array([[  0.,   0.],
       [602.,   0.],
       [602., 233.],
       [  0., 233.]], dtype=float32)

In [ ]:
horizontal_corners[0][x1]
depth_map

array([[1.2148892, 1.2148892, 1.2148892, ..., 1.2148892, 1.2148892,
        1.2148892],
       [1.2149348, 1.2149348, 1.2149348, ..., 1.2149348, 1.2149348,
        1.2149348],
       [1.2150264, 1.2150264, 1.2150264, ..., 1.2150264, 1.2150264,
        1.2150264],
       ...,
       [1.6001883, 1.6001883, 1.6001883, ..., 1.6001883, 1.6001883,
        1.6001883],
       [1.6000677, 1.6000677, 1.6000677, ..., 1.6000677, 1.6000677,
        1.6000677],
       [1.6000075, 1.6000075, 1.6000075, ..., 1.6000075, 1.6000075,
        1.6000075]], dtype=float32)

In [ ]:
# Параметры камеры (пример значения, замените их на реальные)
focal_length = 500
principal_point = (panorama_image.shape[1] / 2, panorama_image.shape[0] / 2)

# Создайте матрицу камеры
camera_matrix = np.array([[focal_length, 0, principal_point[0]],
                          [0, focal_length, principal_point[1]],
                          [0, 0, 1]], dtype=np.float32)

# Используйте undistort для коррекции искажений
undistorted_image = cv2.undistort(panorama_image, camera_matrix, distCoeffs=None)
cv2.find4QuadCornerSubpix
# Сохраните результат
cv2.imwrite("/content/undistorted_panorama_image.jpg", undistorted_image)


True

In [ ]:
#почему-то качает не последнюю версию.
!pip install scikit-image

In [ ]:
!pip install --upgrade scikit-image

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 52.5 MB/s eta 0:00:00
  Attempting uninstall: scikit-image
    Found existing installation: scikit-image 0.19.3
    Uninstalling scikit-image-0.19.3:
      Successfully uninstalled scikit-image-0.19.3


# Попытка использовать remap. Отложена из-за чрезмерного времени на реализацию.

In [ ]:
perspective_matrix = cv2.getPerspectiveTransform(src_points, dst_points)

# Размер целевого изображения
target_size = (wall_width, wall_height)

map_x, map_y = np.meshgrid(np.arange(target_size[0]), np.arange(target_size[1]))

# Преобразуем координаты с использованием матрицы преобразования
transformed_coordinates = np.dot(perspective_matrix, np.vstack([map_x.flatten(), map_y.flatten(), np.ones_like(map_x.flatten())]))

# Нормализуем координаты
normalized_coordinates = (transformed_coordinates[:2, :] / transformed_coordinates[2, :]).T.reshape(target_size[1], target_size[0], 2)

# Используем remap для получения прямоугольного изображения
#result_rectangular = cv2.remap(result, normalized_coordinates, None, interpolation=cv2.INTER_LINEAR)

# Сохраните результат
#cv2.imwrite("/content/rectangular_result.jpg", result_rectangular)


#cv2.initUndistortRectifyMap()

# Попытка кусочно-афинного преобразования. Отложена из-за чрезмерного времени на реализацию и неудовлетворительные промежуточные результаты.

In [ ]:
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
shape1 = x2 - x1 + 1
shape2 = 2
src = np.zeros((shape1 * shape2, 2))
print(type(src[0][0]))
for i in range(shape1):
    ind = i * 2
    src[ind    ][0] = x1 + i
    src[ind + 1][0] = src[ind][0]
    ind2 = int(src[ind][0])
    src[ind    ][1] = horizontal_corners[0][ind2]
    src[ind + 1][1] = horizontal_corners[1][ind2]
src.shape

<class 'numpy.float64'>


(666, 2)

In [ ]:
dst_cols = np.linspace(0, 1204, shape1)
dst_rows = np.linspace(0, 560, 2)
dst_rows, dst_cols = np.meshgrid(dst_rows, dst_cols)
dst = np.dstack([dst_cols.flat, dst_rows.flat])[0]
dst.shape

(666, 2)

In [ ]:
dst

array([[   0.        ,    0.        ],
       [   0.        ,  560.        ],
       [   3.62650602,    0.        ],
       ...,
       [1200.37349398,  560.        ],
       [1204.        ,    0.        ],
       [1204.        ,  560.        ]])

In [ ]:
from skimage.transform import PiecewiseAffineTransform, warp

x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
shape1 = x2 - x1 + 1
shape2 = 2
src = np.zeros((shape1 * shape2, 2))
print(type(src[0][0]))
for i in range(shape1):
    ind = i * 2
    src[ind    ][0] = x1 + i
    src[ind + 1][0] = src[ind][0]
    ind2 = int(src[ind][0])
    src[ind    ][1] = horizontal_corners[0][ind2]
    src[ind + 1][1] = horizontal_corners[1][ind2]

dst_cols = np.linspace(0, 1204 - 1, shape1)
dst_rows = np.linspace(0, 560 - 1, 2)
dst_rows, dst_cols = np.meshgrid(dst_rows, dst_cols)
dst = np.dstack([dst_cols.flat, dst_rows.flat])[0]
dst.shape

tform = PiecewiseAffineTransform()
tform.estimate(src, dst)

out = warp(result, tform, output_shape=(560, 1204))

cv2.imwrite("/content/001.jpg", out)

<class 'numpy.float64'>


True

# depth

In [ ]:
ddd = [[1234, 0] for _ in range(1024)]
for i in range(1024):
    for j in range(horizontal_corners[0][i], horizontal_corners[1][i]):
        if depth_map[j][i] < ddd[i][0]:
            ddd[i][0] = depth_map[j][i]
            ddd[i][1] = j

cnt_other_depth = 0
for v1, v2 in ddd:
    if v2 != 255:
        cnt_other_depth +=1
cnt_other_depth

23

Для стен середина проекции имеет координату 255 почти на всей протяжённости панорамы. Нормаль к плоскости первой стены проходит через точку [255,255]

In [ ]:
min(ddd[31:364])

[1.1305078, 255]

In [ ]:
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
[x1,x2]

[31, 363]

In [ ]:
ddd[250:260] # 255-256 -- median

[[1.1311467, 255],
 [1.1309336, 255],
 [1.1307633, 255],
 [1.1306356, 255],
 [1.1305504, 255],
 [1.1305078, 255],
 [1.1305078, 255],
 [1.1305504, 255],
 [1.1306356, 255],
 [1.1307633, 255]]

In [ ]:
[horizontal_corners[0][255],
horizontal_corners[1][255]]

[123, 411]

In [ ]:
temp_ = [depth_map[255][255], depth_map[123][255], depth_map[411][255]]
am = (temp_[1] ** 2 - temp_[0] ** 2) ** 0.5
mb = (temp_[2] ** 2 - temp_[0] ** 2) ** 0.5
height_prop = [am * 100 / wall_height, mb * 100 / wall_height]
[[am, mb], height_prop]
# камера находилась на высоте ~1.6 метра над землёй.

[[1.1947171704275479, 1.5947711024441236],
 [0.5127541503980892, 0.6844511169288084]]

# Итоговый рабочий вариант. Partfully warpPerspective

In [ ]:

panorama_image_path = "/content/image_1024_aligned_rgb.png"
new_pan = cv2.imread(panorama_image_path, cv2.IMREAD_COLOR)
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
first_point = []
mask = np.zeros_like(new_pan)
y1_max = 512
y2_max = 0
for i in range(x1, x2 + 1):
    mask[horizontal_corners[0][i]: horizontal_corners[1][i], i] = 1
    y1_max = min(y1_max, horizontal_corners[0][i])
    y2_max = max(y2_max, horizontal_corners[1][i])

# Примените маску к панораме
#result = new_pan * mask
#result = result[y1_max:y2_max, x1:x2]
result = new_pan
    # Сохраните результат
cv2.imwrite("/content/1_wall_start.jpg", result)

True

In [ ]:
x_min = x1
x_max = x2

In [ ]:
result.shape

(512, 1024, 3)

In [ ]:
#for j in range(0, len(result[0]), 2):
#    x1 = j
#    x2 = j + 1
#
#    point1 = [x1, horizontal_corners[0][x1] - y1_max]
#    point2 = [x2, horizontal_corners[0][x2] - y1_max]
#    point3 = [x2, horizontal_corners[1][x2] - y1_max]
#    point4 = [x1, horizontal_corners[1][x1] - y1_max]
#
#    width = 2
#    height = y2_max - y1_max
#
#    src_points = np.array([point1, point2, point3, point4], dtype=np.float32)
#    dst_points = np.array([[0, 0], [width, 0], [width, height], [0, height]], dtype=np.float32)
#
#    # Получите матрицу преобразования
#    perspective_matrix = cv2.getPerspectiveTransform(src_points, dst_points)
#
#    # Примените преобразование
#    result_rectangular = cv2.warpPerspective(result, perspective_matrix, (width, height))
#
#    for i in range(len(result_rectangular)):
#        result[i][x1] = result_rectangular[i][0]
#        result[i][x2] = result_rectangular[i][1]

In [ ]:
width = 2
for j in range(x_min, x_max + 1, width):
    x1 = j
    x2 = j + width - 1

    # над высотой камеры
    yy = 255
    point1 = [x1, horizontal_corners[0][x1]]
    point2 = [x2, horizontal_corners[0][x2]]
    point3 = [x2, yy]
    point4 = [x1, yy]

    height = yy - y1_max + 1
    src_points = np.array([point1, point2, point3, point4], dtype=np.float32)
    dst_points = np.array([[0, 0], [width - 1, 0], [width - 1, height - 1], [0, height - 1]], dtype=np.float32)

    # Получите матрицу преобразования
    perspective_matrix = cv2.getPerspectiveTransform(src_points, dst_points)

    # Примените преобразование
    result_rectangular = cv2.warpPerspective(result, perspective_matrix, (width, height))

    for i in range(len(result_rectangular)):
        for j in range(width):
            result[i + y1_max][x1 + j] = result_rectangular[i][j]



    # ниже высоты камеры
    yy = 256
    point1 = [x1, yy]
    point2 = [x2, yy]
    point3 = [x2, horizontal_corners[1][x2]]
    point4 = [x1, horizontal_corners[1][x1]]

    height = y2_max - yy + 1
    src_points = np.array([point1, point2, point3, point4], dtype=np.float32)
    dst_points = np.array([[0, 0], [width - 1, 0], [width - 1, height - 1], [0, height - 1]], dtype=np.float32)

    # Получите матрицу преобразования
    perspective_matrix = cv2.getPerspectiveTransform(src_points, dst_points)

    # Примените преобразование
    result_rectangular = cv2.warpPerspective(result, perspective_matrix, (width, height))

    for i in range(len(result_rectangular)):
        for k in range(width):
            result[i + yy][x1 + k] = result_rectangular[i][k]

In [ ]:
#width = 2
#for j in range(x_min, x_max, width):
#    x1 = j
#    x2 = j + width - 1
#
#    # над высотой камеры
#    yy = 255
#    point1 = [x1, horizontal_corners[0][x1]]
#    point2 = [x2, horizontal_corners[0][x2]]
#    point3 = [x2, yy]
#    point4 = [x1, yy]
#
#    height = yy - y1_max + 1
#    src_points = np.array([point1, point2, point3, point4], dtype=np.float32)
#    dst_points = np.array([[0, 0], [width - 1, 0], [width - 1, height - 1], [0, height - 1]], dtype=np.float32)
#
#    # Получите матрицу преобразования
#    perspective_matrix = cv2.getPerspectiveTransform(src_points, dst_points)
#
#    # Примените преобразование
#    result_rectangular = cv2.warpPerspective(result, perspective_matrix, (width, height))
#
#    for i in range(len(result_rectangular)):
#        result[i + y1_max][x1] = result_rectangular[i][0]
#        result[i + y1_max][x2] = result_rectangular[i][1]
#
#
#    # ниже высоты камеры
#    yy = 256
#    point1 = [x1, yy]
#    point2 = [x2, yy]
#    point3 = [x2, horizontal_corners[1][x2]]
#    point4 = [x1, horizontal_corners[1][x1]]
#
#    height = y2_max - yy + 1
#    src_points = np.array([point1, point2, point3, point4], dtype=np.float32)
#    dst_points = np.array([[0, 0], [width - 1, 0], [width - 1, height - 1], [0, height - 1]], dtype=np.float32)
#
#    # Получите матрицу преобразования
#    perspective_matrix = cv2.getPerspectiveTransform(src_points, dst_points)
#
#    # Примените преобразование
#    result_rectangular = cv2.warpPerspective(result, perspective_matrix, (width, height))
#
#    for i in range(len(result_rectangular)):
#        result[i + yy][x1] = result_rectangular[i][0]
#        result[i + yy][x2] = result_rectangular[i][1]

In [ ]:
cv2.imwrite("/content/1_wall.jpg", result)

True

In [ ]:
# обрезаем фото по стене.
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
result = result[y1_max:y2_max, x1:x2]
#
#    # Сохраните результат
cv2.imwrite("/content/1_wall.jpg", result)

True

Мы получили изображение без учёта глубины.
Дополнительное исследование работы с глубиной.

In [ ]:
depth_map.shape

(512, 1024)

In [ ]:
[x1,x2]

[31, 363]

In [ ]:
center_1_wall = [255, 255]
depth_map[255][255]

1.1305078

In [ ]:
255-31

224

In [ ]:
255-363

-108

In [ ]:
depth_map[255][31]

5.8855715

In [ ]:
depth_1_wall = depth_map[255][31:363]

In [ ]:
center_1_wall = 255-30

In [ ]:
(363-31+1)/4

83.25

In [ ]:
mera = (depth_1_wall[center_1_wall + 3] ** 2 - depth_1_wall[center_1_wall] ** 2) ** 0.5
mera

0.024034907406875267

In [ ]:
(depth_1_wall[center_1_wall - 4] ** 2 - depth_1_wall[center_1_wall] ** 2) ** 0.5

0.024034907406875267

In [ ]:
center_1_wall + 4*34

361

In [ ]:
center_1_wall - 4*56

1

In [ ]:
np.around(((depth_1_wall[center_1_wall + 7] ** 2 - depth_1_wall[center_1_wall] ** 2) ** 0.5 - mera * 1)/mera *4, decimals = 0).astype(int)

5

In [ ]:
depth_1_wall.shape[0]

332

Формируем список векторов по расширению отдельных участков (кусочно) изображения вширь: как координаты, так и то, насколько расширять. Как правее нормали, так и левее её.

In [ ]:
total_size = 0 + 4
ind_size_higher = [[center_1_wall, 4]]
ind = center_1_wall + 3
while ind + 4 < len(depth_1_wall):
    next_size = np.around(((depth_1_wall[ind + 4] ** 2 - depth_1_wall[center_1_wall] ** 2) ** 0.5 - mera * len(ind_size_higher))/mera *4, decimals = 0).astype(int)
    ind_size_higher.append([ind, next_size])
    total_size += next_size
    ind += 4
if ind != depth_1_wall.shape[0] - 1:
    ind -= 4
    total_size -= ind_size_higher[-1][1]
    ind_size_higher.pop()
    step = depth_1_wall.shape[0] - 1 - ind
    next_size = np.around(((depth_1_wall[ind + step] ** 2 - depth_1_wall[center_1_wall] ** 2) ** 0.5 - mera * len(ind_size_higher))
                            / mera * step, decimals = 0).astype(int)
    ind_size_higher.append([ind, next_size])
    total_size += next_size
    ind += step
ind_size_higher.append([ind, 0])
# ind_size_higher


In [ ]:
total_size

472

In [ ]:
total_size += 4
ind = center_1_wall - 4
ind_size_lower = [[ind, 4]]
ind -= 4
while ind >= 0:
    next_size = np.around(((depth_1_wall[ind] ** 2 - depth_1_wall[center_1_wall] ** 2) ** 0.5 - mera * len(ind_size_lower))/mera *4, decimals = 0).astype(int)
    ind_size_lower.insert(0, [ind, next_size])
    total_size += next_size
    ind -= 4
if ind != 0:
    ind += 4 * 2
    total_size -= ind_size_lower[0][1]
    ind_size_lower.pop(0)
    step = ind
    ind = 0
    next_size = np.around(((depth_1_wall[0] ** 2 - depth_1_wall[center_1_wall] ** 2) ** 0.5 - mera * len(ind_size_lower))
                            / mera * step, decimals = 0).astype(int)
    ind_size_lower.insert(0, [0, next_size])
    total_size += next_size
    ind = 0
#ind_size_lower

In [ ]:
ind_size = ind_size_lower + ind_size_higher
# ind_size

In [ ]:
new_res = np.zeros((result.shape[0], total_size, result.shape[2]), dtype=np.uint8)
new_res.shape

(288, 7414, 3)

In [ ]:
height = result.shape[0]
xx = 0
for j in range(len(ind_size) - 1):
    width = ind_size[j + 1][0] - ind_size[j][0]
    x1 = ind_size[j][0]
    x2 = x1 + width - 1

    # над высотой камеры
    yy = 255
    point1 = [x1, 0]
    point2 = [x2, 0]
    point3 = [x2, height - 1]
    point4 = [x1, height - 1]


    src_points = np.array([point1, point2, point3, point4], dtype=np.float32)
    dst_points = np.array([[0, 0], [ind_size[j][1] - 1, 0], [ind_size[j][1] - 1, height - 1], [0, height - 1]], dtype=np.float32)

    # Получите матрицу преобразования
    perspective_matrix = cv2.getPerspectiveTransform(src_points, dst_points)

    # Примените преобразование
    result_rectangular = cv2.warpPerspective(result, perspective_matrix, (ind_size[j][1], height))

    for i in range(len(result_rectangular)):
        for k in range(ind_size[j][1]):
            new_res[i][xx + k] = result_rectangular[i][k]
    xx += ind_size[j][1]

In [ ]:
cv2.imwrite("/content/1_wall_final.jpg", new_res)

True

In [ ]:
new_width = 602
new_height = 280

# Сжимаем изображение до нового размера
resized_image = cv2.resize(new_res, (new_width, new_height))

In [ ]:
# получаем итоговое изображение с поправкой на соотношение сторон 6.02 и 2.8 метра
cv2.imwrite("/content/1_wall_final.jpg", resized_image)

True

# undistort. Отложена из-за чрезмерного времени на реалзиацию в условиях неидеально, но работающего warpPerspective

In [ ]:
panorama_image_path = "/content/image_1024_aligned_rgb.png"
new_pan = cv2.imread(panorama_image_path, cv2.IMREAD_COLOR)
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
first_point = []
mask = np.zeros_like(new_pan)
y1_max = 512
y2_max = 0
for i in range(x1, x2 + 1):
    mask[horizontal_corners[0][i]: horizontal_corners[1][i], i] = 1
    y1_max = min(y1_max, horizontal_corners[0][i])
    y2_max = max(y2_max, horizontal_corners[1][i])

# Примените маску к панораме
#result = new_pan * mask
#result = result[y1_max:y2_max, x1:x2]
result = new_pan[y1_max:y2_max, x1:x2]
    # Сохраните результат
cv2.imwrite("/content/1_wall_und.jpg", result)

True

In [ ]:
x1 = vertical_corners[0][0]
x2 = vertical_corners[2][0]
shape1 = x2 - x1 + 1

shape2 = 3
src = np.zeros((shape1 * shape2, 2))
for i in range(shape1):
    ind = i * shape2
    src[ind    ][0] = i
    src[ind + 1][0] = src[ind][0]
    src[ind + 2][0] = src[ind][0]
    ind2 = int(src[ind][0] + x1)
    src[ind    ][1] = horizontal_corners[0][ind2] - y1_max
    src[ind + 1][1] = (horizontal_corners[1][ind2] + horizontal_corners[0][ind2]) / 2 - y1_max
    src[ind + 2][1] = horizontal_corners[1][ind2] - y1_max
new_src = np.zeros((shape1 * shape2, 2))
for i in range(shape1):
    new_src[i] = src[3 * i]
    new_src[i + shape1] = src[3 * i + 1]
    new_src[i + shape1 * 2] = src[3 * i + 2]
src = new_src
src = [np.array(src, dtype=np.float32)]
src[0]

array([[  0.,  99.],
       [  1.,  99.],
       [  2.,  98.],
       ...,
       [330., 271.],
       [331., 270.],
       [332., 270.]], dtype=float32)

In [ ]:
dst_cols = np.linspace(0, shape1 - 1, shape1)
dst_rows = np.linspace(0, y2_max - y1_max,  shape2)
dst_rows, dst_cols = np.meshgrid(dst_rows, dst_cols)
dst = np.dstack([dst_cols.flat, dst_rows.flat])[0]
new_src = np.zeros((shape1 * shape2, 2))
for i in range(shape1):
    new_src[i] = dst[3 * i]
    new_src[i + shape1] = dst[3 * i + 1]
    new_src[i + shape1 * 2] = dst[3 * i + 2]
dst = new_src
dst = [np.array([list(x) + [0] for x in dst], dtype=np.float32)]
dst[0]

array([[  0.,   0.,   0.],
       [  1.,   0.,   0.],
       [  2.,   0.,   0.],
       ...,
       [330., 288.,   0.],
       [331., 288.,   0.],
       [332., 288.,   0.]], dtype=float32)

In [ ]:
width = shape1
height = y2_max - y1_max

In [ ]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(dst, src, (width, height), None, None)

undistorted_img = cv2.undistort(result, mtx, dist, None, mtx)

In [ ]:
cv2.imwrite("/content/11111.jpg", undistorted_img)

True

# 2 undistort. Попытка добавить больше точек

In [ ]:
shape1 = 1024
shape2 = 3

src = np.zeros((shape1 * shape2, 2))
for i in range(shape1):
    ind = i * shape2
    src[ind    ][0] = i
    src[ind + 1][0] = src[ind][0]
    src[ind + 2][0] = src[ind][0]
    ind2 = i
    src[ind    ][1] = horizontal_corners[0][ind2] - y1_max
    src[ind + 1][1] = (horizontal_corners[1][ind2] + horizontal_corners[0][ind2]) / 2 - y1_max
    src[ind + 2][1] = horizontal_corners[1][ind2] - y1_max
new_src = np.zeros((shape1 * shape2, 2))
for i in range(shape1):
    new_src[i] = src[3 * i]
    new_src[i + shape1] = src[3 * i + 1]
    new_src[i + shape1 * 2] = src[3 * i + 2]
src = new_src
src = [np.array(src, dtype=np.float32)]

In [ ]:
dst_cols = np.linspace(0, shape1 - 1, shape1)
dst_rows = np.linspace(0, 511,  shape2)
dst_rows, dst_cols = np.meshgrid(dst_rows, dst_cols)
dst = np.dstack([dst_cols.flat, dst_rows.flat])[0]
new_src = np.zeros((shape1 * shape2, 2))
for i in range(shape1):
    new_src[i] = dst[3 * i]
    new_src[i + shape1] = dst[3 * i + 1]
    new_src[i + shape1 * 2] = dst[3 * i + 2]
dst = new_src
dst = [np.array([list(x) + [0] for x in dst], dtype=np.float32)]
dst[0].shape

(3072, 3)

In [ ]:
width = 1024
height = 512

In [ ]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(dst, src, (width, height), None, None)

undistorted_img = cv2.undistort(panorama_image, mtx, dist, None, mtx)

In [ ]:
cv2.imwrite("/content/22222.jpg", undistorted_img)

True